name = "pokopia-portal"
compatibility_date = "2024-01-01"
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "pokopia-db"
database_id = "b2a8c21c-efbd-42af-ae65-76d6b9ce6fe9"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "pokopia-media"

[[kv_namespaces]]
binding = "CACHE"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
